[package]
name = "ai"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.25.1"
rand = "0.8.5"
savefile = "0.17.7"
savefile-derive = "0.17.7"

[profile.release]
debug = true
